### ISSUE TITLE
Querying with date range do not work

### ISSUE THREAD

**Issue by WeijiaZhang24** [GLAM-Workbench/trove-newspaper-harvester#12]
Hi,

I am doing some research in digital humanity and Trove. Your repository is a great help of my research! However, I encountered a small issue when using the TroveHarvester. Would you please help me out?

For example, if I use "https://trove.nla.gov.au/search/advanced/category/newspapers?date.from=1852-01-01&date.to=1954-12-31" as a query and my query looks like "python -m troveharvester start https://trove.nla.gov.au/search/advanced/category/newspapers?date.from=1852-01-01&date.to=1954-12-31 API-Key". 

Then the program will throw a message saying "The system cannot accept the date entered."                 

Best Regards,
Weijia Zhang

**Comment by wragge** [comment]
Hi,

I'm glad you're finding it useful!

I'm not able to reproduce your exact error, but could you try enclosing the query in quotes? 
```
troveharvester start "https://trove.nla.gov.au/search/advanced/category/newspapers?date.from=1852-01-01&date.to=1954-12-31" YOUR-API-KEY
```
This works fine for me.

Cheers!

**Comment by WeijiaZhang24** [comment]
That works! 
Thanks for the quick response :)
